<?php

/**
 * Class Model_All_Groups - Модель для страницы groups
 */
class Model_All_Groups extends Model
{
    /**
     * Список быстрых комманд на странице
     */
    function getActionButtons(){
        return array(
            "Добавить группу" => "group/add",
            "Выставить счет" => "bill/add",
            "Добавить клиента" => "customer/add",
            "Добавить препода" => "teacher/add"
        );
    }

    function get_data()
    {
        //return parent::get_data(); // TODO: Change the autogenerated stub
        return Class_Create_Simple_Table::html($this->headerTable(),$this->getAllGroups());
    }

    /**
     * Список групп
     */
    function getAllGroups(){
        $listGroups = array();
        $obj = new Model_Groups(array("where"=>"del = 0", "order" => "name ASC"));
        if(!$obj->num_row){
            /**
             * Поумолчанию если нет данных
             */
            $listGroups[] = array(
                'class_tr' => 'table-light',
                'tds' => array(
                    "pp"        => 1,
                    "id"        =>'1',
                    "period"    => 'Нет данных',
                    "groupName" => 'Нет данных',
                    "daysWeak"  => 'Нет данных',
                    "maxUsers"  => 'Нет данных',
                    "teachers"  => 'Нет данных',
                    "action"    => 'Нет данных'
                )
            );
        }else{
            $rows = $obj->getAllRows();
            foreach ($rows AS $item){
                $strDay = '';
                if($item['mon']) $strDay .="mon, ";
                if($item['tue']) $strDay .="tue, ";
                if($item['wed']) $strDay .="wed, ";
                if($item['thu']) $strDay .="thu, ";
                if($item['fri']) $strDay .="fri, ";
                if($item['sat']) $strDay .="sat, ";
                if($item['sun']) $strDay .="sun, ";
                $listGroups[] = array(
                    'class_tr' => 'table-light',
                    'tds' => array(
                        "pp"        => 1,
                        "id"        => $item['id'],
                        "period"    => date("d.m.Y", $item['dt_start']).'-'.date("d.m.Y", $item['dt_end']),
                        "groupName" => '<a href="/group?id='.$item['id'].'">'.$item['name'].'</a>',
                        "daysWeak"  => trim($strDay, ", "),
                        "maxUsers"  => $item['max_user'],
                        "teachers"  => $item['id'],
                        "action"    => 'Нет данных'
                    )
                );
            }
        }

        return $listGroups;
    }

    function headerTable(){
        return array("ПП", "Ид", "Период", "Название", "Дни недели", "Места", "Преподаватели", "Действия");
    }
}